name: test

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check-last-update
      id: to-update
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const runs = github.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_file_name: 'blog.yml'
            })
          console.log(runs)
          const updateTimeStr = runs.workflow_runs[0].updated_at
          const now = new Date()
          const last = new Date(updateTimeStr)
          const td = (now - last)/60000 // in minutes
          return (td > 30) || (context.github.event !== 'repository_dispatch')